name: threshold_custom
description: Custom package from threshold.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
publish_to: none
dependencies:
  # path: ^1.8.0
  archive: ^4.0.7
  lzstring_custom:
    git:
      url: https://github.com/faizin4107/lzstring_custom.git
      ref: 1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
